config/routes.rb
Rails.application.routes.draw do
  resources :birds

end

app/models/bird.rb
class Bird < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/birds_controller.rb
class BirdsController < ApplicationController
  before_action :set_bird, only: [:show, :edit, :update, :destroy]

  # GET /birds
  # GET /birds.json
  def index
    @birds = Bird.all
  end

  # GET /birds/1
  # GET /birds/1.json
  def show
  end

  # GET /birds/new
  def new
    @bird = Bird.new
  end

  # GET /birds/1/edit
  def edit
  end

  # POST /birds
  # POST /birds.json
  def create
    @bird = Bird.new(bird_params)

    respond_to do |format|
      if @bird.save
        format.html { redirect_to @bird, notice: 'Bird was successfully created.' }
        format.json { render :show, status: :created, location: @bird }
      else
        format.html { render :new }
        format.json { render json: @bird.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /birds/1
  # PATCH/PUT /birds/1.json
  def update
    respond_to do |format|
      if @bird.update(bird_params)
        format.html { redirect_to @bird, notice: 'Bird was successfully updated.' }
        format.json { render :show, status: :ok, location: @bird }
      else
        format.html { render :edit }
        format.json { render json: @bird.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /birds/1
  # DELETE /birds/1.json
  def destroy
    @bird.destroy
    respond_to do |format|
      format.html { redirect_to birds_url, notice: 'Bird was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bird
      @bird = Bird.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bird_params
      params.require(:bird).permit(:name, :variant, :weight, :mugshot)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/birds_helper.rb
module BirdsHelper
end

app/views/birds/_form.html.erb
<%= form_for(@bird) do |f| %>
  <% if @bird.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bird.errors.count, "error") %> prohibited this bird from being saved:</h2>

      <ul>
      <% @bird.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :variant %><br>
    <%= f.text_field :variant %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :mugshot %><br>
    <%= f.text_field :mugshot %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/birds/edit.html.erb
<h1>Editing Bird</h1>

<%= render 'form' %>

<%= link_to 'Show', @bird %> |
<%= link_to 'Back', birds_path %>

app/views/birds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Birds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Variant</th>
      <th>Weight</th>
      <th>Mugshot</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @birds.each do |bird| %>
      <tr>
        <td><%= bird.name %></td>
        <td><%= bird.variant %></td>
        <td><%= bird.weight %></td>
        <td><%= bird.mugshot %></td>
        <td><%= link_to 'Show', bird %></td>
        <td><%= link_to 'Edit', edit_bird_path(bird) %></td>
        <td><%= link_to 'Destroy', bird, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bird', new_bird_path %>

app/views/birds/new.html.erb
<h1>New Bird</h1>

<%= render 'form' %>

<%= link_to 'Back', birds_path %>

app/views/birds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bird.name %>
</p>

<p>
  <strong>Variant:</strong>
  <%= @bird.variant %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @bird.weight %>
</p>

<p>
  <strong>Mugshot:</strong>
  <%= image_tag(@bird.mugshot) %>
</p>

<%= link_to 'Edit', edit_bird_path(@bird) %> |
<%= link_to 'Back', birds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Birds</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>